package com.example.myapplication.ui.theme

import androidx.compose.ui.graphics.Color

// Hyper-Purple Vibrant Scheme

// Light Theme
val PrimaryLight = Color(0xFF8E00D1)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFF6D9FF)
val OnPrimaryContainerLight = Color(0xFF2F004C)
val SecondaryLight = Color(0xFF6B5872)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFF3DAFA)
val OnSecondaryContainerLight = Color(0xFF25162C)
val TertiaryLight = Color(0xFF8B4A60)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFD9E2)
val OnTertiaryContainerLight = Color(0xFF3A071D)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFFF7FD)
val OnBackgroundLight = Color(0xFF1E1A1F)
val SurfaceLight = Color(0xFFFFF7FD)
val OnSurfaceLight = Color(0xFF1E1A1F)
val SurfaceVariantLight = Color(0xFFE9DFEB)
val OnSurfaceVariantLight = Color(0xFF4A454E)
val OutlineLight = Color(0xFF7B757F)

// Dark Theme
val PrimaryDark = Color(0xFFE9B3FF)
val OnPrimaryDark = Color(0xFF4C0076)
val PrimaryContainerDark = Color(0xFF660099)
val OnPrimaryContainerDark = Color(0xFFF6D9FF)
val SecondaryDark = Color(0xFFD7BEE0)
val OnSecondaryDark = Color(0xFF3B2B42)
val SecondaryContainerDark = Color(0xFF534159)
val OnSecondaryContainerDark = Color(0xFFF3DAFA)
val TertiaryDark = Color(0xFFFFB1C8)
val OnTertiaryDark = Color(0xFF541D32)
val TertiaryContainerDark = Color(0xFF703348)
val OnTertiaryContainerDark = Color(0xFFFFD9E2)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF161217)
val OnBackgroundDark = Color(0xFFE9E0E6)
val SurfaceDark = Color(0xFF161217)
val OnSurfaceDark = Color(0xFFE9E0E6)
val SurfaceVariantDark = Color(0xFF4A454E)
val OnSurfaceVariantDark = Color(0xFFCBC4CF)
val OutlineDark = Color(0xFF958E99)
